name: DevOps CI pipeline

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout/v3

      - name: List Files
        run: ls -la

      - name: Show current Directory
        run: pwd

      - name: print system info
        run: uname -a
 
      - name: Stimulate build
        run: echo "Building application..."

      - name: Stimulate Test
        run: echo "Running Test..."

      - name: Stimulate success
        run: echo "Build and Test Successful"
